Revert "Overhaul 'repair' handling in audits"
This reverts commit a212243c287002ca35beb81802deb2abb29f4033.

Reason for revert: 

Sorry but this needs more work and doesn't actually work in my testing of the first 2 audits I tried (app catalog and coe)

Error is:

2021-07-22 19:06:10,031 nectar_tools.audit.coe.cluster WARNING 39f25431-a569-4ec8-9e91-e2a7829ae117 - in DELETE_FAILED state
2021-07-22 19:06:10,031 nectar_tools.audit.base ERROR 'bool' object is not callable
Traceback (most recent call last):
  File "/home/sam/projects/nectar-tools/nectar_tools/audit/base.py", line 38, in run_all
    getattr(self, method)(**kwargs)
  File "/home/sam/projects/nectar-tools/nectar_tools/audit/coe/cluster.py", line 46, in check_status
    self._delete_cluster(cluster)
  File "/home/sam/projects/nectar-tools/nectar_tools/audit/coe/cluster.py", line 18, in _delete_cluster
    self.repair(lambda: self.client.clusters.delete(cluster.uuid),
TypeError: 'bool' object is not callable

Change-Id: Iee95a080635293f7316adea8d0a0932e3c453098